### ISSUE TITLE
Script for launching development environment...

### ISSUE THREAD

**Issue by manor** [NYUMetabolomics/The-Executive-Board#10]
Currently starting up the system correctly involves at least 4 terminals... In the near future this may become unwieldy. Maybe Docker? Or a nice bash script to launch everything? (This might also circumvent Issue [#7](https://github.com/NYUMetabolomics/The-Executive-Board/issues/7))

Note that this could also deal with setting up a valid directory structure (e.g. ../efs) along with the file types in ../efs/files.

**Comment by yiksiu** [comment]
This will be part of https://github.com/NYUMetabolomics/The-Executive-Board/issues/24, so I will close this one for now.
