### ISSUE TITLE
Provenance Key

### ISSUE THREAD

**Issue by DrewRJones** [NYUMetabolomics/The-Executive-Board#12]
![image](https://github.com/NYUMetabolomics/The-Executive-Board/assets/27428342/6384686d-37fd-47eb-bba9-5f2a681d284d)

Change node display to show full length of "node hash" which should be renamed to "Provenance Key". Throughout the interface don't use the word "Hash" but change it to "Key". Emphasize the provenance key, show short keys for script and output file.

**Comment by yiksiu** [comment]
updated
