### ISSUE TITLE
Upload Delay / Upload Size Too Large (Crash)

### ISSUE THREAD

**Issue by DrewRJones** [NYUMetabolomics/The-Executive-Board#14]
![image](https://github.com/NYUMetabolomics/The-Executive-Board/assets/27428342/22e979bf-da0d-4ba6-b98b-d9ae3e8f0f31)

1) Upload fails if file  >~2GB (instance memory)

2) ~1min delay before network traffic starts actually uploading the file

**Comment by yiksiu** [comment]
This is no longer an issue after the new chunk file upload update. I will mark it as closed for now.
