### ISSUE TITLE
JSON error handling

### ISSUE THREAD

**Issue by DrewRJones** [NYUMetabolomics/The-Executive-Board#2]
![image](https://github.com/NYUMetabolomics/The-Executive-Board/assets/27428342/d65f2e01-7adf-417d-adfa-9ba9f91f375c)

I uploaded an edited JSON script which was accepted (removed the "value:") but then when the script was dragged to the workspace (SQ1211-1213) the system crashed. Upon resigning in, the workspace is still crashed if entered, but the rest of the workspaces are ok

**Comment by yiksiu** [comment]
The schema.json file validation function is completed and uploaded with the most recent update
