### ISSUE TITLE
Script editing navigation

### ISSUE THREAD

**Issue by DrewRJones** [NYUMetabolomics/The-Executive-Board#3]
![image](https://github.com/NYUMetabolomics/The-Executive-Board/assets/27428342/5dc27ea5-df0a-422e-ab0f-3d3d4980a66f)

Often want to edit a script/node, but starting from inside a workflow. There should be a button to view the script/JSON on the node. Also we need a full screen script editor

**Comment by yiksiu** [comment]
This function was added with the most recent updates
