### ISSUE TITLE
Error when selecting a version in History tab

### ISSUE THREAD

**Issue by tranphibaochau** [NYUMetabolomics/The-Executive-Board#34]
How to replicate: 
Choose Lab Space-> Choose Workspace -> Choose History Tab -> Default Timeline View -> Click on a version in the history (might need to click multiple times), and it gives an error shown below:
![image](https://github.com/user-attachments/assets/abd2ed8e-9bc8-42b8-9475-7d244c6c6b16)

**Comment by yiksiu** [comment]
This bug should be fixed by the most recent update
