### ISSUE TITLE
GUI Kill Process Button

### ISSUE THREAD

**Issue by DrewRJones** [NYUMetabolomics/The-Executive-Board#5]
![image](https://github.com/NYUMetabolomics/The-Executive-Board/assets/27428342/a1b0f261-7293-48f7-a257-464ddcfff7f3)

Valid script but will take years of compute time. Users need to have a GUI button to kill a spinning process

**Comment by DrewRJones** [comment]
We should add the spinning wheel icon to the history pane to see which workspace configurations have active procesess so users can go kill those nodes

**Comment by yiksiu** [comment]
The cancel running process function has been added to the current server implementation. I will mark it as closed for now.
