### ISSUE TITLE
Node State not correctly checking history

### ISSUE THREAD

**Issue by DrewRJones** [NYUMetabolomics/The-Executive-Board#8]
![image](https://github.com/NYUMetabolomics/The-Executive-Board/assets/27428342/23d553c9-0ca9-4a54-95a9-e954da27a9d6)

An already executed state is not being detected, instead the node code is attempting to run

**Comment by yiksiu** [comment]
This is due to different versions of the layout stored and the backend logic. This is no longer an issue for the current backend design.
