### ISSUE TITLE
CSS Layout Issue on dataset upload

### ISSUE THREAD

**Issue by manor** [NYUMetabolomics/The-Executive-Board#9]
This happened when uploading a data file:

![layout_issue_data_upload](https://github.com/NYUMetabolomics/The-Executive-Board/assets/596326/b927f7d7-91c3-4012-91af-eec558ac27c9)

**Comment by yiksiu** [comment]
Updated with the new layout
![image](https://github.com/NYUMetabolomics/The-Executive-Board/assets/76179146/452fb9ad-18c9-4e41-984c-e9d57c91223f)
